# yaml-language-server: $schema=https://raw.githubusercontent.com/streetsidesoftware/cspell/main/packages/cspell-tools/cspell-tools.config.schema.json

targets:
  - name: "godot"
    sources:
      - filename: "src/godot.txt"
        maxDepth: 1
        keepRawCase: true
      - filename: "src/config.txt"
        maxDepth: 1
        keepRawCase: true
      - filename: "src/filetypes.txt"
        maxDepth: 1
        keepRawCase: true
      - filename: "src/gdscript.txt"
        maxDepth: 1
        keepRawCase: true
      - filename: "src/globals-and-keywords.txt"
        maxDepth: 1
        keepRawCase: true
      - filename: "src/sharp-script.txt"
        maxDepth: 1
        keepRawCase: true
    format: "plaintext"
    targetDirectory: "./dict"
    generateNonStrict: false
    compress: false
